---
- name: Shrink logical volumes
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  debugger: on_failed
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - kernel
  roles:
    - shrink_lv
